from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
import io
from datetime import datetime

def generate_scan_report(url, prediction, trust_score, recommendations, features=None):
    """
    Generate a PDF report for the URL scan results.
    Returns a BytesIO buffer containing the PDF.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=18,
        spaceAfter=30,
        alignment=1  # Center
    )

    heading_style = ParagraphStyle(
        'Heading',
        parent=styles['Heading2'],
        fontSize=14,
        spaceAfter=15
    )

    normal_style = styles['Normal']

    # Content
    story = []

    # Title
    story.append(Paragraph("Phishing Detection Scan Report", title_style))
    story.append(Spacer(1, 12))

    # Scan Date
    scan_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    story.append(Paragraph(f"Scan Date: {scan_date}", normal_style))
    story.append(Spacer(1, 12))

    # URL Scanned
    story.append(Paragraph("URL Scanned:", heading_style))
    story.append(Paragraph(url, normal_style))
    story.append(Spacer(1, 12))

    # Scan Results
    story.append(Paragraph("Scan Results:", heading_style))

    # Create results table
    result_data = [
        ['Parameter', 'Value'],
        ['Status', 'Safe' if prediction == 1 else 'Not Safe'],
        ['Trust Score', f'{trust_score}%'],
        ['Risk Level', 'Low' if trust_score >= 70 else 'Medium' if trust_score >= 40 else 'High']
    ]

    result_table = Table(result_data, colWidths=[2*inch, 3*inch])
    result_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 14),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))

    story.append(result_table)
    story.append(Spacer(1, 12))

    # Recommendations
    story.append(Paragraph("Recommendations:", heading_style))
    for rec in recommendations:
        story.append(Paragraph(f"• {rec}", normal_style))
        story.append(Spacer(1, 6))

    story.append(Spacer(1, 12))

    # Feature Analysis (if available)
    if features:
        story.append(Paragraph("Technical Analysis:", heading_style))
        feature_descriptions = [
            "Using IP Address",
            "URL Length",
            "Short URL",
            "Contains @ Symbol",
            "Redirecting",
            "Prefix/Suffix in Domain",
            "Number of Subdomains",
            "HTTPS Usage",
            "Domain Registration Length",
            "Favicon",
            "Non-Standard Port",
            "HTTPS in Domain URL",
            "Request URL",
            "Anchor URL",
            "Links in Script Tags",
            "Server Form Handler",
            "Info Email",
            "Abnormal URL",
            "Website Forwarding",
            "Status Bar Customization",
            "Disable Right Click",
            "Using Popup Window",
            "Iframe Redirection",
            "Age of Domain",
            "DNS Recording",
            "Website Traffic",
            "Page Rank",
            "Google Index",
            "Links Pointing to Page",
            "Stats Report"
        ]

        feature_data = [['Feature', 'Value']]
        for i, (desc, val) in enumerate(zip(feature_descriptions[:len(features)], features)):
            feature_data.append([desc, 'Safe' if val == 1 else 'Suspicious' if val == -1 else 'Neutral'])

        feature_table = Table(feature_data, colWidths=[3*inch, 2*inch])
        feature_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))

        story.append(feature_table)

    # Footer
    story.append(Spacer(1, 24))
    story.append(Paragraph("This report was generated by SecureSurf Phishing Detector", styles['Italic']))
    story.append(Paragraph("For security awareness and educational purposes only.", styles['Italic']))

    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer
